ngrx/router

lib/guard.ts, lib/index.ts, lib/match-pattern.ts, lib/match-route.ts, lib/route-set.ts
Previously we were running guards as part of route traversal. This PR refactors route traversal to expose a middleware hook called traversal middleware. 
They run before a route is traversed and transform a stream of routes into a stream of boolean values. If the stream returns false, the traverser aborts traversing that route.
Refactored guards to use traversal middleware.
=> Adds Traversal Middleware

lib/location.ts, lib/query-params.ts, lib/route-set.ts, spec/location.spec.ts, spec/query-params.spec.ts
LocationChange events are now more consistent and useful. The go and replaceState methods now accept objects instead of just query strings.
=> fix(Location): Cleaned up Location service

LICENSE, package.json
Updates copyright notice to include original copyright holders.
Files that came from react-router:
* `/lib/match-pattern.ts`
* `/lib/match-route.ts`
cc @mjackson and @ryanflorence
=> chore(License): Updated copyright notice

lib/link-active.ts, spec/link-active.spec.ts
Initial implementation. Still need to write tests. Currently supports the linkTo element, or a corresponding child linkTo element. Also allows you to keep parent links active when visiting their child links using the `activeOptions` input. Also doesn't take into account for query parameters, which are optional by nature, but we could expand the options to include testing them if needed.
In the case below, if you visit the Parent, it will be active, and if you visit the child both will be active.
```html
<a linkTo="/parent" linkActive="active" [activeOptions]="{ exact: false }">Parent Link</a>
<a linkTo="/parent/child" linkActive="active">Child Link</a>
````
cc: @MikeRyan52 @fxck
=> feat(directives): Added linkActive directive

lib/guard.ts, lib/index.ts, lib/match-route.ts, lib/util.ts, spec/guard.spec.ts, spec/link-to.spec.ts
Traversal middleware now receives the matched route, a preview of route params, and whether or not traversal plans on terminating on that route. Traversal middleware can:
* Null out the route to stop traversing that route
* Mark the candidate as terminal to force traversal to select that route
* If the route is marked as terminal it can modify the final route params
With this change, guards will only run if the route they are installed on is an actual candidate. This should make it safe to perform redirections inside of guards. They also now receive a preview of route params as their second argument.
cc @laurelnaiad and @fxck
=> Improved Traversal Middleware

lib/match-route.ts, spec/match-route.spec.ts
Previous algorithm would have given favor to the route that finished first. This would be problematic if you had a long running guard on a root route. The router would have selected 404 instead of that route because your 404 route would finish first. Switching to concat instead of merge fixes this problem.
=> fix(MatchRoute): Give favor to the order in which routes are defined

docs/getting-started/code-splitting.md, docs/getting-started/guards.md, lib/component-renderer.ts, lib/match-route.ts, lib/resource-loader.ts, lib/route.ts, lib/util.ts, spec/component-renderer.spec.ts, spec/match-route.spec.ts, spec/util.spec.ts
Promises are more zone-aware than callbacks. They also work better with rx operators like mergeMap, switchMap, etc.
BREAKING CHANGE: Before loadComponent, loadChildren, and loadIndexRoute used a callback to handle async loading of code. These must be replaced with promise-returning functions.
Before:
```ts
{
loadIndex(done) {
System.import('./my-index-route', __moduleName)
.then(module => done(module.indexRoute));
},
loadComponent(done) {
System.import('./my-component', __moduleName)
.then(module => done(module.MyComponent));
},
loadChildren(done) {
System.import('./child-routes', __moduleName)
.then(module => done(module.routes));
}
}
```
After:
```ts
{
loadIndex: () => System.import('./my-index-route', __moduleName)
.then(module => module.indexRoute),
loadComponent: () => …
```
=> feat(AsyncConfig): Refactor route config to use promises instead of callbacks

docs/getting-started/code-splitting.md, docs/getting-started/route.md, lib/component-renderer.ts, lib/route-view.ts, lib/route.ts, spec/component-renderer.spec.ts, spec/route-view.spec.ts, spec/route.spec.ts
Route config can now accept named components
Using `components`:
```ts
const routes: Routes = [
{
path: '/blog',
components: {
main: Blog,
sideMenu: RecentPosts
}
}
]
```
Using `loadComponents`:
```ts
export const routes: Routes = [
{
path: '/blog',
loadComponents: {
main: () => System.import('/app/blog.ts')
.then(module => module.BlogPage),
sideMenu: () => System.import('/app/recent-posts.ts')
.then(module => module.RecentPosts)
}
}
];
```
Route views must be given a name to enable named component mode:
```html
<route-view name="main"></route-view>
```
Without a name, they'll default to using `component` or `loadComponent`
Closes #6
=> feat(NamedComponents): Add ability to configure named components

docs/overview/guards.md, docs/overview/params.md, lib/index.ts, lib/link-active.ts, lib/link-to.ts, lib/redirect.ts, lib/router-instruction.ts, lib/router.ts, spec/component-renderer.spec.ts, spec/link-active.spec.ts, spec/link-to.spec.ts, spec/redirect.spec.ts, spec/route-set.spec.ts, spec/router.spec.ts, spec/tsconfig.json
BREAKING CHANGE: Renamed `Location` service to `Router` and renamed `replaceState` method to `replace`
Before:
```ts
import { Location } from '@ngrx/router';
class App {
constructor(location: Location) {
location.replaceState('/path', { query: 1 });
}
}
```
After:
```ts
import { Router } from '@ngrx/router';
class App {
constructor(router: Router) {
router.replace('/path', { query: 1 });
}
}
```
=> refactor(location): Renamed Location service to Router

lib/guard.ts, spec/guard.spec.ts
Change guard factory from `createGuard` to `provideGuard` to clarify what the factory is doing. Re-order guard params to receive route params first.
BREAKING CHANGE:
Before:
```ts
const auth = createGuard(function(http: Http) {
return function(route: Route, params: any, isTerminal: boolean) {
return http.get(...);
};
}, [ Http ]);
```
After:
```ts
const auth = provideGuard(function(http: Http) {
return function(params: any, route: Route, isTerminal: boolean) {
return http.get(...);
};
}, [ Http ]);
```
=> refactor(Guards): Improve guards API based on common usage

lib/router-instruction.ts, lib/zone.ts, spec/router-instruction.spec.ts, spec/tsconfig.json
@robwormald Can you take a look at the ZoneOperator and let me know if this is roughly what you were thinking? It uses NgZone to pass values into the destination subscriber.
=> fix(RouterInstruction): Pass the subscriber back through NgZone

lib/link-active.ts, spec/link-active.spec.ts
=> fix(LinkActive): Fixed active link for base url when using hash

docs/overview/guards.md, lib/guard.ts, lib/route.ts, spec/guard.spec.ts
Before we used `provideGuard` to quickly create guard factory functions. In order to play better with the offline compiler, this changes guards to instead use traditional services.
BREAKING CHANGE:
Before:
```ts
const auth = provideGuard(function(http: Http) {
return function(route: Route, params: any, isTerminal: boolean): Observable<boolean> {
return http.get('/auth')
.map(() => true)
.catch(() => Observable.of(false));
};
}, [ Http ]);
```
After:
```ts
@Injectable()
export class AuthGuard implements Guard {
constructor(private http: Http) { }
protectRoute({ route, params, isTerminal }: TraversalCandidate): Observable<boolean> {
return this.http.get('/auth')
.map(() => true)
.catch(() => Observable.of(false));
}
}
```
=> refactor(Guards): Re-implement guards feature to use services

docs/overview/guards.md, lib/index.ts, lib/redirect.ts, lib/route-traverser.ts, lib/route-view.ts, lib/router-instruction.ts, spec/guard.spec.ts, spec/params.spec.ts, spec/redirect.spec.ts, spec/route-traverser.spec.ts, spec/route-view.spec.ts, spec/router-instruction.spec.ts
Traverser now accepts a LocationChange instead of a pathname. Returned Match now includes the LocationChange and the query params. RouterInstruction is no longer responsible for parsing query params. Guards now receive query params and the location change as a result of this refactoring.
BREAKING CHANGE:
TraversalCandidate interface has renamed `params` to `routeParams` and now includes queryParams and locationChange.
Before:
```ts
const { params, isTerminal, route } = traversalCandidate;
```
After:
```ts
const { routeParams, queryParams, isTerminal, route, locationChange } = traversalCandidate;
```
=> refactor(RouteTraverser): Expand traverser to also track query params and location changes

lib/route-traverser.ts, lib/route.ts, spec/route-traverser.spec.ts
BREAKING CHANGE:
`indexRoute` is now `index` and `loadIndexRoute` is now `loadIndex`
BEFORE:
```ts
const routes: Routes = [
{
path: '/',
component: MarketingTemplateComponent,
indexRoute: {
component: HomePageComponent,
}
},
{
path: '/blog',
component: BlogComponent,
loadIndexRoute: () => System.import('app/routes/blog')
}
];
```
AFTER:
```ts
const routes: Routes = [
{
path: '/',
component: MarketingTemplateComponent,
index: {
component: HomePageComponent
}
},
{
path: '/blog',
component: BlogComponent,
loadIndex: () => System.import('app/routes/blog')
}
];
```
=> refactor(routes): Rename `indexRoute` and `loadIndexRoute`

lib/index.ts, lib/router-instruction.ts
Strategy for ngrx/store bindings is to re-bind the location changes observable with a projection from Store.
=> feat(RouteInstruction): Decouple Router from RouteInstruction

lib/route-traverser.ts, spec/route-traverser.spec.ts
Before we ignored nested child routes that contained a forward slash at the beginning of the path. This was to potentially allow for absolute path URLs in nested routes, however there is no way to make this feature work with async route configuration. This change removes this restriction and allows you to add a forward slash at the beginning of the path with no functional difference.
=> feat(RouteTraverser): Allow forward slash in nested route paths

docs/overview/guards.md
There is no such method .redirect() on Router. Update to correct one.
=> fix(docs): Use correct method for redirect

docs/overview/params.md
The can get rid of this warning in the terminal:
> Type '{}' is not assignable to type 'string'.
=> add <string> for .pluck

docs/overview/links.md, lib/index.ts, lib/link-active.ts, spec/link-active.spec.ts
=> feat(LinkActive): Added override of default activeOptions

README.md, docs/overview/webpack.md
Was getting errors like this when trying to integrate with the Angular 2 Webpack Starter:
WARNING in ./~/@ngrx/router/index.js
Cannot find source file '../../lib/index.ts': Error: Cannot resolve 'file' or 'directory' ../../lib/index.ts in /home/select/Dev/shoutr-srv/client/node_modules/@ngrx/router
Found the solution on gitter here: https://gitter.im/ngrx/store/archives/2016/04/26, and thought I should share with everyone else.
=> updated docs to include webpack config

docs/overview/location-strategy.md
Links were pointing to a 404 page because those pages have been moved.
=> Updating links to angular documentation
